### PR TITLE
Tiny gender specific update

### PR DESCRIPTION
**Pull request by KnorpelSenf**
There's always a bunch of people who care. So why not make it more comfortable for them.

### CODE REVIEW

**Comment by domoritz** [comment]
👍

**Comment by jgraichen** [comment]
Could you adjust the failing specs to the new wording?

**Comment by KnorpelSenf** [comment]
> Could you adjust the failing specs to the new wording?

I would if I knew how things work here and what to to.
Could you a) point me to where I can find such things as specifications (tutorial?) or b) adjust them yourself?
The general idea behind my change is to use gender neutral language. Some find this a little bit "annoying", but most people don't even notice. And then there's a bunch of people who are really idealistic about it and who boycott to visit websites if they find -- so to say -- incorrect words. At universities, it seems like the ratio of people of the latter kind is unusually high.That's the reason for my change.
In specific, the word "Studenten" refers to a group of male and female students, but it can be understood as a group of men only (in contrast to "Studentinnen", women only). "Studierende" does not imply such things and is perfectly equal among both (all) genders.

**Comment by domoritz** [comment]
You can check the Travis logs for the failing test. https://travis-ci.org/openmensa/openmensa/builds/442081648?utm_source=github_status&utm_medium=notification

**Comment by KnorpelSenf** [comment]
Thank you! That should do it.

**Pull request merged**
